# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('inventario', models.CharField(max_length=5)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
    ]
